package com.wondersgroup.falcon.model.jhk;

import java.util.Date;

/**
 * AppHlpdoc generated by MyEclipse Persistence Tools
 */

public class AppHlpdoc implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String id;
	
	private String title;				//文档标题	
	private String type;				//文档类型(0-业务指南;1-操作指南)
	private Date publishdate;			//最后发布时间
	private String busisysid;			//所属业务系统编码
	private String busimenuid;			//所属业务系统对应菜单或功能编号
	//private Clob content;				//文件正文
	//private String neirongstring;  	//临时
	private String content;			//文档内容
	private String keyword;				//搜索关键字，多个之间用空格分开

	// Constructors

	/** default constructor */
	public AppHlpdoc() {
	}

	/** minimal constructor */
	public AppHlpdoc(String id) {
		this.id = id;
	}

	/** full constructor */
	public AppHlpdoc(String id, String title, String type, Date publishdate,
			String busisysid, String busimenuid, String content, String keyword) {
		this.id = id;
		this.title = title;
		this.type = type;
		this.publishdate = publishdate;
		this.busisysid = busisysid;
		this.busimenuid = busimenuid;
		this.content = content;
		this.keyword = keyword;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getPublishdate() {
		return this.publishdate;
	}

	public void setPublishdate(Date publishdate) {
		this.publishdate = publishdate;
	}

	public String getBusisysid() {
		return this.busisysid;
	}

	public void setBusisysid(String busisysid) {
		this.busisysid = busisysid;
	}

	public String getBusimenuid() {
		return this.busimenuid;
	}

	public void setBusimenuid(String busimenuid) {
		this.busimenuid = busimenuid;
	}



	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}



}