package com.wondersgroup.falcon.model.jhk;

import java.util.Date;

/**
 * AppUsersynexg generated by MyEclipse Persistence Tools
 */

public class AppUsersynexg implements java.io.Serializable {

	// Fields

	private String id;

	private String userid;

	private Date createdate;

	private String usersynid;

	private String systemcode;

	private String busiuserid;

	private String busiuserlogin;

	private String busiuserpwd;

	private String exgtype;

	private String createlogid;

	private String name;

	private String sex;

	private String accounttype;

	private String email;

	private String address;

	private String mobile;

	private String fax;

	private String homePhone;

	private String officePhone;

	private String status;

	private String busiorganid;

	// Constructors

	/** default constructor */
	public AppUsersynexg() {
	}

	/** minimal constructor */
	public AppUsersynexg(String id) {
		this.id = id;
	}

	/** full constructor */
	public AppUsersynexg(String id, String userid, Date createdate,
			String usersynid, String systemcode, String busiuserid,
			String busiuserlogin, String busiuserpwd, String exgtype,
			String createlogid, String name, String sex, String accounttype,
			String email, String address, String mobile, String fax,
			String homePhone, String officePhone, String status,
			String busiorganid) {
		this.id = id;
		this.userid = userid;
		this.createdate = createdate;
		this.usersynid = usersynid;
		this.systemcode = systemcode;
		this.busiuserid = busiuserid;
		this.busiuserlogin = busiuserlogin;
		this.busiuserpwd = busiuserpwd;
		this.exgtype = exgtype;
		this.createlogid = createlogid;
		this.name = name;
		this.sex = sex;
		this.accounttype = accounttype;
		this.email = email;
		this.address = address;
		this.mobile = mobile;
		this.fax = fax;
		this.homePhone = homePhone;
		this.officePhone = officePhone;
		this.status = status;
		this.busiorganid = busiorganid;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getUsersynid() {
		return this.usersynid;
	}

	public void setUsersynid(String usersynid) {
		this.usersynid = usersynid;
	}

	public String getSystemcode() {
		return this.systemcode;
	}

	public void setSystemcode(String systemcode) {
		this.systemcode = systemcode;
	}

	public String getBusiuserid() {
		return this.busiuserid;
	}

	public void setBusiuserid(String busiuserid) {
		this.busiuserid = busiuserid;
	}

	public String getBusiuserlogin() {
		return this.busiuserlogin;
	}

	public void setBusiuserlogin(String busiuserlogin) {
		this.busiuserlogin = busiuserlogin;
	}

	public String getBusiuserpwd() {
		return this.busiuserpwd;
	}

	public void setBusiuserpwd(String busiuserpwd) {
		this.busiuserpwd = busiuserpwd;
	}

	public String getExgtype() {
		return this.exgtype;
	}

	public void setExgtype(String exgtype) {
		this.exgtype = exgtype;
	}

	public String getCreatelogid() {
		return this.createlogid;
	}

	public void setCreatelogid(String createlogid) {
		this.createlogid = createlogid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAccounttype() {
		return this.accounttype;
	}

	public void setAccounttype(String accounttype) {
		this.accounttype = accounttype;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBusiorganid() {
		return this.busiorganid;
	}

	public void setBusiorganid(String busiorganid) {
		this.busiorganid = busiorganid;
	}

}