package com.wondersgroup.falcon.model.jhk;

import java.util.Date;

/**
 * AppUsersynans generated by MyEclipse Persistence Tools
 */

public class AppUsersynans implements java.io.Serializable {

	// Fields

	private String id;

	private String userexgid;

	private Date createdate;

	private String synopt;

	private String busiuserid;

	// Constructors

	/** default constructor */
	public AppUsersynans() {
	}

	/** minimal constructor */
	public AppUsersynans(String id) {
		this.id = id;
	}

	/** full constructor */
	public AppUsersynans(String id, String userexgid, Date createdate,
			String synopt, String busiuserid) {
		this.id = id;
		this.userexgid = userexgid;
		this.createdate = createdate;
		this.synopt = synopt;
		this.busiuserid = busiuserid;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserexgid() {
		return this.userexgid;
	}

	public void setUserexgid(String userexgid) {
		this.userexgid = userexgid;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getSynopt() {
		return this.synopt;
	}

	public void setSynopt(String synopt) {
		this.synopt = synopt;
	}

	public String getBusiuserid() {
		return this.busiuserid;
	}

	public void setBusiuserid(String busiuserid) {
		this.busiuserid = busiuserid;
	}

}