package com.wondersgroup.kaoshi.bo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EExercise generated by MyEclipse Persistence Tools
 */

public class EExercise implements java.io.Serializable {

	// Fields

	private Long lxId;

	private String lxRyid;
	
	private String lxRyxm;

	private Date lxKssj;

	private Date lxJssj;

	private Long lxDtsl;

	private Long lxKgtsl;

	private Double lxKgtzql;

	private Set EExercisequestionses = new HashSet(0);

	// Constructors

	/** default constructor */
	public EExercise() {
	}

	/** minimal constructor */
	public EExercise(Long lxId, String lxRyid, Date lxKssj, Date lxJssj,
			Long lxDtsl) {
		this.lxId = lxId;
		this.lxRyid = lxRyid;
		this.lxKssj = lxKssj;
		this.lxJssj = lxJssj;
		this.lxDtsl = lxDtsl;
		this.lxRyxm = lxRyxm;
	}

	/** full constructor */
	public EExercise(Long lxId, String lxRyid, Date lxKssj, Date lxJssj,
			Long lxDtsl, Long lxKgtsl, Double lxKgtzql, Set EExercisequestionses) {
		this.lxId = lxId;
		this.lxRyid = lxRyid;
		this.lxKssj = lxKssj;
		this.lxJssj = lxJssj;
		this.lxDtsl = lxDtsl;
		this.lxKgtsl = lxKgtsl;
		this.lxKgtzql = lxKgtzql;
		this.lxRyxm = lxRyxm;
		this.EExercisequestionses = EExercisequestionses;
	}

	// Property accessors

	public Long getLxId() {
		return this.lxId;
	}

	public void setLxId(Long lxId) {
		this.lxId = lxId;
	}

	public String getLxRyid() {
		return this.lxRyid;
	}

	public void setLxRyid(String lxRyid) {
		this.lxRyid = lxRyid;
	}

	public Date getLxKssj() {
		return this.lxKssj;
	}

	public void setLxKssj(Date lxKssj) {
		this.lxKssj = lxKssj;
	}

	public Date getLxJssj() {
		return this.lxJssj;
	}

	public void setLxJssj(Date lxJssj) {
		this.lxJssj = lxJssj;
	}

	public Long getLxDtsl() {
		return this.lxDtsl;
	}

	public void setLxDtsl(Long lxDtsl) {
		this.lxDtsl = lxDtsl;
	}

	public Long getLxKgtsl() {
		return this.lxKgtsl;
	}

	public void setLxKgtsl(Long lxKgtsl) {
		this.lxKgtsl = lxKgtsl;
	}

	public Double getLxKgtzql() {
		return this.lxKgtzql;
	}

	public void setLxKgtzql(Double lxKgtzql) {
		this.lxKgtzql = lxKgtzql;
	}

	public Set getEExercisequestionses() {
		return this.EExercisequestionses;
	}

	public void setEExercisequestionses(Set EExercisequestionses) {
		this.EExercisequestionses = EExercisequestionses;
	}

	public String getLxRyxm() {
		return lxRyxm;
	}

	public void setLxRyxm(String lxRyxm) {
		this.lxRyxm = lxRyxm;
	}

}