package com.wondersgroup.kaoshi.bo;

import com.wondersgroup.falcon.question.model.EQuestions;

/**
 * EExercisequestions generated by MyEclipse Persistence Tools
 */

public class EExercisequestions implements java.io.Serializable {

	// Fields

	private Long id;

	private EExercise EExercise;

	private EQuestions equestions;

	private String stDa;

	private String stDasm;

	// Constructors

	/** default constructor */
	public EExercisequestions() {
	}

	/** minimal constructor */
	public EExercisequestions(Long id, EExercise EExercise, Long stId,
			String stDa) {
		this.id = id;
		this.EExercise = EExercise;
		this.stDa = stDa;
	}

	/** full constructor */
	public EExercisequestions(Long id, EExercise EExercise, Long stId,
			String stDa, String stDasm) {
		this.id = id;
		this.EExercise = EExercise;
		this.stDa = stDa;
		this.stDasm = stDasm;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public EExercise getEExercise() {
		return this.EExercise;
	}

	public void setEExercise(EExercise EExercise) {
		this.EExercise = EExercise;
	}


	public EQuestions getEquestions() {
		return equestions;
	}

	public void setEquestions(EQuestions equestions) {
		this.equestions = equestions;
	}

	public String getStDa() {
		return this.stDa;
	}

	public void setStDa(String stDa) {
		this.stDa = stDa;
	}

	public String getStDasm() {
		return this.stDasm;
	}

	public void setStDasm(String stDasm) {
		this.stDasm = stDasm;
	}

}